### ISSUE TITLE
Homebrew is required message when Homebrew is already installed

### ISSUE THREAD

**Issue by thislogancall** [Supernova-Studio/public-issue-tracker#54]
Attempting to export Spacebook w/out any modifications to React Native. Getting a message that says Homebrew is required when I already have it installed.

When running `brew -v` in terminal
```
$ brew -v
Homebrew 1.5.10
```

Here's a screenshot:

![image](https://user-images.githubusercontent.com/5152553/37479058-4a1c15a4-2841-11e8-88e5-a1494a2c940b.png)

**Comment by vovanmix** [comment]
+1, I have the same problem!

**Comment by manosteele91827** [comment]
+1, Same Problem here

**Comment by artufimtcev** [comment]
So we have fixed this one, will be available in V4.

**Comment by IlyasAbdighni** [comment]
I am having the same issue in V4.4
Brew version: 1.7.6
Supernova version: 4.4
MacOS: Macos high sierra

Can anyone help me?

**Comment by artufimtcev** [comment]
@IlyasAbdighni could you post a screenshot of the error message that you're getting?

**Comment by JiriTrecak** [comment]
@IlyasAbdighni can you please run `which brew` in the terminal and give us the precise result?

**Comment by IlyasAbdighni** [comment]
These are the screenshots: 
<img width="146" alt="screen shot 2018-10-02 at 3 38 27 pm" src="https://user-images.githubusercontent.com/15980838/46352121-4d88cc80-c659-11e8-9e0f-69284760379e.png">
![screen shot 2018-10-02 at 3 38 48 pm](https://user-images.githubusercontent.com/15980838/46352131-51b4ea00-c659-11e8-981f-2a667e6cf937.png)

**Comment by JiriTrecak** [comment]
We'll test it. The reason is your terminal coloring library, it malforms the output of the terminal, so it never gives the result we need to check for the installation directory. Can you give us the name of the terminal lib you use (or if you use custom terminal)?

**Comment by IlyasAbdighni** [comment]
Thank you for quick response. I use iTerm2 + zsh + oh-my-zsh togethor. I hope this is helpfull.

**Comment by fahidmohammad** [comment]
What is the solution for this issue? and why did this issue closed without a proper solution?

**Comment by artufimtcev** [comment]
@fahidmohammad this issue was closed because this particular cause was solved on our end. Now if you see it as well, that means there's another issue blocking Supernova from using brew on your computer, and if that's the case feel free to open this issue again and provide some details on what exactly is happening to you. On the side note, we are working on CLI independent project exporters for Supernova, so all those things should be fixed soon as Supernova won't access terminal on your computer at all.

**Comment by hopewise** [comment]
I've downloaded the trial today, and I got the same problem.. I am out of ideas

**Comment by jan-supernova** [comment]
Hey!
This issue has been resolved. If this issue still persists, let us know!

Have a wonderful day!
Jan, Supernova Team

**Comment by rascyber** [comment]
Hi,

I am getting same error means the issue still persist. 
`brew -v
Homebrew 2.3.0
`
